
version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      # for services to communicate with RabbitMQ
      - 5672:5672
      # for us to navigate the RabbitMQ portal
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    # specify a place name for RabbitMQ to store data at
    hostname: rabbitmq

volumes:
  mongodbdata:
  rabbitmqdata: